data_dir: ./examples/
raw_path: er_cell_data.npz
save_path: ./examples/checkpoint/er/
num_epoch: 500
batch_size: 2
l2_loss_margin: 2
line_spacing: [0.419529, 0.419209, 0.419530]
k0angles: [1.781592, 2.897372, -2.379572]
ndirs: 3
na: 1.28
ri_medium: 1.33
wavelength: 0.515
ps: 0.040625
ps_otf: 0.040625
dz: 0.15
dz_otf: 0.1
zoomfact: 1.6
lr_init_motion: 5e-5
lr_init_object: 5e-3
lr_init_modamp: 0
annealed_rate: 0.8
object_hash_base: [3, 30, 30]
object_hash_fine: [10, 300, 300]
motion_hash_base: [4, 1, 1, 1]
motion_hash_fine: [12, 30, 30, 5]
nonneg_reg_w: 5e-6
update_every_motion: 1
update_every_object: 1
padding_z: 2
